### ISSUE TITLE
Request failed. HTTP CODE: 302

### ISSUE THREAD

**Issue by ghost** [RasmusLindroth/OMDb-PHP-API#4]
I downloaded this sample but i'm getting `Request failed. HTTP CODE: 302` . I changed api key of course.

**Comment by RasmusLindroth** [comment]
The HTTP 302 means there is a redirection to an other URL. I haven't seen that before with this API. But it maybe works if you tell curl to follow redirects. Test to check out this branch (the link under this text) instead of master and see if that works.

https://github.com/RasmusLindroth/OMDb-PHP-API/tree/test-redirect

Otherwise you could give me an example where you get that error and I will try to fix it

**Comment by RasmusLindroth** [comment]
No response, so I assumes there's no issue
